from models import CharacterRecord,POVClaim,AssetReference
P=lambda t,c="SUPPORTED",p=(): POVClaim(t,c,p)
RECORDS=[
CharacterRecord("2.0","CHAR-JAKE-KALOPER","Jake Kaloper","ObiWan Jacoby","The Trade Jedi",species_body="youthful blond human strategist",head_face="youthful blond human",silhouette="human strategist in earth-tone field/Jedi layers with green energy sword",materials="earth-tone cloth/leather field layers",wardrobe=("earth-tone Jedi-inspired robes","field jacket"),signature_objects=("green energy sword",),companions=("golden retriever",),environment_anchor="North Georgia mountain war-room",negative_locks=("championship belt","masked soldier","dark wizard","generic knight"),hard_locks=("NO CHAMPIONSHIP BELT",),primary_asset_id="REF-JAKE-001",pov=(P("strategy, leverage, timing and preparation","ESTABLISHED",("Weekly Memo canon",)),)),
CharacterRecord("2.0","CHAR-KEVIN-ZEEK","Kevin Zeek","Red Leopards","The Predator Board",species_body="giant anthropomorphic red leopard/jaguar",head_face="red feline head with black rosettes and amber eyes",silhouette="large feline predator with claws and tribal armor",materials="red fur, black rosettes, ancient/tribal armor",signature_objects=("claws",),environment_anchor="jungle ruins",negative_locks=("human hunter","species/color change"),primary_asset_id="REF-KEVIN-001",pov=(P("predation, patience and pursuit"),)),
CharacterRecord("2.0","CHAR-JORDAN-HOLLINGSHEAD","Jordan Hollingshead","Slob on my Dobb","Frat-Bro Berserker",aliases=("Frat Star","Win Ugly"),species_body="huge horned shaggy human-beast berserker",head_face="horned shaggy berserker",silhouette="massive filthy football berserker",materials="shaggy hair/fur, battered football materials",wardrobe=("battered football armor","filthy Slob shirt"),signature_objects=("metal bat","beer"),companions=("pit-bull",),environment_anchor="tailgate/bar football chaos",negative_locks=("clean","slim","polished","generic football player"),primary_asset_id="REF-JORDAN-001",pov=(P("chaotic excess, ugly survival and irreverent victory"),)),
CharacterRecord("2.0","CHAR-DAVID-BABB","David Babb","The LLC.","Hostile Takeover",aliases=("The LLC",),species_body="human corporate raider",head_face="human with sunglasses",silhouette="tailored executive with cigar/briefcase",materials="dark tailored suiting, leather, gold",wardrobe=("dark tailored three-piece suit","sunglasses"),signature_objects=("LLC briefcase","cigar"),environment_anchor="dark boardroom/market",negative_locks=("animal mascot","fantasy warrior"),primary_asset_id="REF-DAVID-001",pov=(P("control, risk management and monetizing disaster"),)),
CharacterRecord("2.0","CHAR-WILSON-LOOK","Wilson Look","D0nkey K0ng","Arsenal Gorilla Centaur Warrior",aliases=("Donkey Kong","Baker Moore Purdy","Arsenal Gorilla Warrior","Arsenal Centaur","Philosopher-Warrior"),active_version="2.1",species_body="ONE hybrid body: gorilla head/upper identity and powerful armored upper torso integrated with a FOUR-LEGGED centaur/equine lower body",head_face="black-furred gorilla head/face with dark primate features and roaring/fanged expression",silhouette="one continuous gorilla-centaur warlord: powerful gorilla/humanoid upper body over four-legged equine lower body",materials="black fur, Arsenal-red football-warrior armor, bronze/gold metal",wardrobe=("Arsenal-red jersey/armor","Arsenal supporter/cannon heraldry"),signature_objects=("ornate double-headed battle axe","metal tankard"),environment_anchor="monumental high-fantasy battlefield / Arsenal stronghold",negative_locks=("generic bipedal gorilla","horse-headed centaur","human rider on horse","separate gorilla plus horse","two-creature substitute","human-only barbarian","generic jungle mascot","Arsenal identity omitted"),hard_locks=("ONE BODY","GORILLA HEAD/UPPER IDENTITY","FOUR-LEGGED CENTAUR LOWER BODY","ARSENAL SUPPORTER IDENTITY"),primary_asset_id="REF-WILSON-001",pov=(P("force, confidence and warlord momentum"),)),
CharacterRecord("2.0","CHAR-PHILLIP-PITTS","Phillip Pitts","Three Dreaded Snake","The Podium Shadow",species_body="ONE powerful reptilian humanoid BODY with exactly THREE serpent HEADS",head_face="three distinct serpent heads with glowing eyes and dreadlock-like extensions",silhouette="one massive humanoid reptilian body supporting three readable serpent heads",materials="green/gold scales, dark football-warrior materials",wardrobe=("dark #3 football gear",),environment_anchor="jungle/waterfall",negative_locks=("three separate snakes","single-headed reptile","Medusa","human","extra heads","generic hydra"),hard_locks=("ONE BODY","EXACTLY THREE SERPENT HEADS"),primary_asset_id="REF-PHILLIP-001",pov=(P("wounded menace and recovery pressure","SUPPORTED",("Weekly Memo storytelling",)),P("multi-headed vigilance","PROPOSED",("character-form inference; requires narrative approval",)))),
CharacterRecord("2.0","CHAR-BRANDON-PRYOR","Brandon Pryor","Chili Cheesers","The Chili Outlaw",species_body="bearded human Western outlaw/pitmaster",head_face="bearded human with sunglasses and black chili-detail cowboy hat",silhouette="Western outlaw in chili-red duster with pepper bandolier",materials="weathered leather/cloth, chili-red accents",wardrobe=("black cowboy hat","sunglasses","chili-red duster","pepper bandolier"),signature_objects=("chili vessel",),companions=("The Dark Horse",),environment_anchor="dark Western stable/hideout",negative_locks=("retired bear","bloodhound","Chili King","Chili Beast","Chili Gremlin","generic cowboy"),primary_asset_id="REF-BRANDON-001",pov=(P("volatile outlaw confidence; pranks and hospitality becoming consequences","SUPPORTED",("Weekly Memo chili-dog storyline",)),)),
CharacterRecord("2.0","CHAR-MANNING-WELTY","Manning Welty","El Niño","The Weather System",aliases=("El Nino",),species_body="nonhuman storm/water/lightning elemental humanoid",head_face="elemental face with glowing blue eyes",silhouette="humanoid weather mass with cyclone motifs",materials="water, spray, cloud and lightning",signature_objects=("storm staff",),environment_anchor="flooded football stadium",negative_locks=("child","ordinary human","surfer","generic wizard","simple hurricane mascot"),primary_asset_id="REF-MANNING-001",pov=(P("inevitability and environmental pressure"),)),
CharacterRecord("2.0","CHAR-AUSTIN-BYARS","Austin Byars","His Majesty's Blood","The Belt Keeper",aliases=("The Immortal","That's Fantasy"),species_body="towering supernatural humanoid champion",head_face="hooded/shadowed head with supernatural glowing eyes; hidden anatomy not overclaimed",silhouette="towering dark armored champion with belt and sword",materials="layered black armor/cloak, metal/leather/cloth, championship gold",wardrobe=("layered black medieval armor","dark cloak/hood"),signature_objects=("championship belt","medieval/rune sword"),environment_anchor="gothic dark-fantasy championship/relic environment",negative_locks=("king/crown redesign","vampire","blood creature","generic knight","belt omission","rename-driven anatomy"),hard_locks=("championship belt identity-critical",),primary_asset_id="REF-AUSTIN-001",pov=(P("championship memory, burden and survival","ESTABLISHED",("2025 championship history","Week 3 Memo",)),)),
CharacterRecord("2.0","CHAR-BOBBY-MITCHELL","Bobby Mitchell","Mud Dogs","Swamp-Born Menace",species_body="massive rabid mud-covered dog/wolf beast",head_face="feral canine with diseased teeth",silhouette="huge mud-soaked chained canine menace",materials="mud, wet fur, blue/orange accents, metal chain",signature_objects=("heavy chain",),environment_anchor="violent swamp",negative_locks=("normal pet dog","clean/cartoon canine","human hunter"),primary_asset_id="REF-BOBBY-001",pov=(P("territorial resilience; rankings and polish mean little in the swamp"),)),
CharacterRecord("2.0","CHAR-ZACH-WILSON","Zach Wilson","Dr. Duckhook","King of the Impossible Lie",species_body="anthropomorphic white duck golfer",head_face="white duck head with orange bill",silhouette="duck golfer with driver/prosthetic-arm concept",materials="feathers, golf textiles, club metal",wardrobe=("bucket hat","golf outfit"),signature_objects=("driver prosthetic arm","golf equipment","cigar"),environment_anchor="swamp/water golf environment",negative_locks=("normal duck","human golfer","physician","generic golf mascot"),primary_asset_id="REF-ZACH-001",pov=(P("competitive absurdity treated with country-club seriousness","ESTABLISHED",("Weekly Memo Duckhook stories",)),)),
CharacterRecord("2.0","CHAR-BEN-WHIPPLE","Ben Whipple","Seven Deadly Chins","The People's Champ",aliases=("Blue-Collar Spoiler",),species_body="very large heavyset bearded human bruiser",head_face="heavyset bearded human",silhouette="large bruiser in dirty tank and trucker cap with hammer",materials="dirty cotton, workwear, metal hammer",wardrobe=("dirty white tank","CHIN UP SHUT UP trucker cap"),signature_objects=("oversized hammer","40-ounce bottle"),companions=("raccoon",),environment_anchor="truck-stop BBQ",negative_locks=("fit/polished redesign","literal multi-chinned monster"),primary_asset_id="REF-BEN-001",pov=(P("blue-collar defiance, stubbornness and improvised force"),)),
]
ASSETS={
"REF-JAKE-001":AssetReference("REF-JAKE-001","PRIMARY_IDENTITY","e9b6690899566864fc9d56b3bc9dbce0e1eb43a2901d23c0949170be4da91e58","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
"REF-KEVIN-001":AssetReference("REF-KEVIN-001","PRIMARY_IDENTITY","df597e71aed77ddf510fd81f3fcd4ee812ac22b8f8e129e276dc5edfbd9dddc1","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
"REF-JORDAN-001":AssetReference("REF-JORDAN-001","PRIMARY_IDENTITY","c052e8c74939338517f1b14bbca5f2ea3d57146794f675d065698a44fb1064e8","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
"REF-DAVID-001":AssetReference("REF-DAVID-001","PRIMARY_IDENTITY","ce3137d1472d63deb7a026d114d200f338d2461d3d223647f34b473794e1f85b","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
"REF-WILSON-001":AssetReference("REF-WILSON-001","PRIMARY_IDENTITY","d6279c5ca904c20de1e5800490d1fed42aa24c8674d051654b29838291459a10","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
"REF-PHILLIP-001":AssetReference("REF-PHILLIP-001","PRIMARY_IDENTITY","31b9d7be295ba662b1332897ef7c33e2f64e92aeefb2d6abe625c08bac914c0c","PENDING_INGESTION",provenance="Commissioner legacy-low 2026-09-29"),
"REF-BRANDON-001":AssetReference("REF-BRANDON-001","PRIMARY_IDENTITY","0bb99794f3a0b9fa1a7f791e17e6885fffcca4b79c824057623bab5c74598cfe","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
"REF-MANNING-001":AssetReference("REF-MANNING-001","PRIMARY_IDENTITY","5e43eadf7ea6426ea8ba2c3af80c108714638625db5adc9d5a32492ff84fc965","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
"REF-AUSTIN-001":AssetReference("REF-AUSTIN-001","PRIMARY_IDENTITY","eedfaaf0b2e2dd78a7a32e11aef333cab41278c206b65ec78c4aa4f1fd2c4f76","PENDING_INGESTION",provenance="Commissioner legacy-low 2026-09-29"),
"REF-BOBBY-001":AssetReference("REF-BOBBY-001","PRIMARY_IDENTITY","4ad8693d7f155f2ee99722f87eb74ea99490eebdfe0b30ca2f17f05004e7cf12","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
"REF-ZACH-001":AssetReference("REF-ZACH-001","PRIMARY_IDENTITY","c8124a1f1146c0acc65b5e82d1c21289afd6a74a8ac2046895e39794619dcefb","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
"REF-BEN-001":AssetReference("REF-BEN-001","PRIMARY_IDENTITY","c4401f79783637c9e3974f02de20ba5aeb1209e7ed4e0f5620e2bfcce3b270cf","PENDING_INGESTION",provenance="Commissioner 2026-09-29"),
}
